### ISSUE TITLE
Scroll speed ?

### ISSUE THREAD

**Issue by starchild** [CodyHouse/cd-carousel-changelog#6]
Hi,

I'm trying to slow the speed of the actual scrolling of the carousel - but I don't see a var for that.

Am I missing it somehow?

Thank you :)

**Comment by sebastiano-guerriero** [comment]
Hi there,

You can edit the transition duration of the .carousel__list--animating:

```css
.carousel__list--animating {
  transition: transform 0.5s var(--ease-out);
}
```

We're going to update the carousel by adding a CSS custom property for the duration.
